# Generated by Django 4.2.7 on 2023-12-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ccal", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=50)),
                ("weight_initial", models.PositiveIntegerField()),
                ("weight_goal", models.PositiveIntegerField()),
                ("daily_ccal", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfilesProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eat_date", models.DateField(auto_now_add=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mainapp.product",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mainapp.profile",
                    ),
                ),
            ],
        ),
    ]
